UniversitySystemWeb/Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversitySystemWeb.Models;

namespace UniversitySystemWeb.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly GraderDBContext _context;

        public ProfessorsController(GraderDBContext context)
        {
            _context = context;
        }

        // GET: Professors
        public async Task<IActionResult> Index(string username)
        {
            var professor = await _context.Professors
                .Include(s => s.UsersUsernameNavigation)
                .FirstOrDefaultAsync(m=> m.UsersUsername==username);
            ViewBag.id = professor.Afm;
            if (professor != null)
            {
                return View(professor);
            }
            return NotFound();
        }

        



    

        public async Task<IActionResult> ViewGrade(int? id,string cTitle = "") 
        {
            
            ViewBag.id = id;
            var courses = (from course in _context.Courses
                          join courseGrades in _context.CourseHasStudents on course.IdCourse equals courseGrades.CourseIdCourse
                          into result
                          from item in result
                          join prof in _context.Professors on course.ProfessorsAfm equals prof.Afm
                          where item.GradeCourseStudent != null && course.ProfessorsAfm==id
                          select new ViewModel
                          { grade = (int)item.GradeCourseStudent, title = course.CourseTitle, semester = course.CourseSemester, registrationNumber = (int)item.StudentsRegistrationNumber }).OrderBy(x=>x.semester);

            var titles = new List<string>(courses.Select(x => x.title).Distinct());
            List<SelectListItem> courseTitles  = titles.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.ToString(),
                    Value = a.ToString(),
                    Selected = false
                };
            });
            
            ViewBag.cTitle = cTitle;

            ViewBag.courseTitles = courseTitles;
            if (courses != null) 
            {
                return View(courses);
            }             
            return View();
        }

        public async Task<IActionResult> ViewNotGraded(int? id)
        {
           
            ViewBag.id = id;
            var courses = (from course in _context.Courses
                          join courseGrades in _context.CourseHasStudents on course.IdCourse equals courseGrades.CourseIdCourse
                          into result
                          from item in result
                          join prof in _context.Professors on course.ProfessorsAfm equals prof.Afm
                          where item.GradeCourseStudent == null && course.ProfessorsAfm == id
                           select new ViewModel
                          { title = course.CourseTitle, semester = course.CourseSemester, registrationNumber = (int)item.StudentsRegistrationNumber,professorId = (int)id, courseId=item.CourseIdCourse }).OrderBy(x=>x.semester);
            
            if (courses != null)
            {
                return View(courses);
            }
            return View();
        }

        public IActionResult Create(string username)
        {
            ViewData["UsersUsername"] = new SelectList(_context.Users, "Username", "Username");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string username,[Bind("Afm,Name,Surname,Department,UsersUsername")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professor);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Secretaries", new { username = username });
            }
            return NotFound();
            
        }




        private bool ProfessorExists(int id)
        {
          return _context.Professors.Any(e => e.Afm == id);
        }
        private bool CourseHasStudentExists(int id)
        {
            return _context.CourseHasStudents.Any(e => e.CourseIdCourse == id);
        }
    }
}

UniversitySystemWeb/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversitySystemWeb.Models;

namespace UniversitySystemWeb.Controllers
{
    public class StudentsController : Controller
    {
        private readonly GraderDBContext _context;

        public StudentsController(GraderDBContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index(string username)
        {
            var student = await _context.Students
                .Include(s => s.UsersUsernameNavigation)
                .FirstOrDefaultAsync(m=> m.UsersUsername==username);
            ViewBag.id = student.RegistrationNumber;
            if (student!=null) 
            {
                return View(student);
            }
            return NotFound(); 
        }

       


        public async Task<IActionResult> GradePerCourse(int? id)
        {
            var student = await _context.Students
               .Include(s => s.UsersUsernameNavigation)
               .FirstOrDefaultAsync(m => m.RegistrationNumber == id);
            var grade = (from stud in _context.Students
                         join courseGrades in _context.CourseHasStudents on stud.RegistrationNumber equals courseGrades.StudentsRegistrationNumber
                         into res1
                         from item in res1
                         join course in _context.Courses on item.CourseIdCourse equals course.IdCourse
                         where stud.RegistrationNumber == id && item.GradeCourseStudent != null
                        select new ViewModel
                         {grade = (int)item.GradeCourseStudent, title = course.CourseTitle, semester = course.CourseSemester }).OrderBy(x => x.semester);
            ViewBag.id = student.RegistrationNumber;
            if (grade != null)
            {
                return View(grade);
            }
            return View();
        }

        
        public async Task<IActionResult> GradePerSemester(int? id,string semester="1")
        {

            var student = await _context.Students
                 .Include(s => s.UsersUsernameNavigation)
                 .FirstOrDefaultAsync(m => m.RegistrationNumber == id);
            ViewBag.id = student.RegistrationNumber;
            if (student == null)
            {
                return NotFound();
            }
            var courses = from stud in _context.Students
                          join courseGrades in _context.CourseHasStudents on stud.RegistrationNumber equals courseGrades.StudentsRegistrationNumber
                          into res1
                          from item in res1
                          join course in _context.Courses on item.CourseIdCourse equals course.IdCourse
                          where stud.RegistrationNumber == id && course.CourseSemester == semester && item.GradeCourseStudent != null
                          select new ViewModel
                          { grade = (int)item.GradeCourseStudent, title = course.CourseTitle, semester = course.CourseSemester, registrationNumber = (int)item.StudentsRegistrationNumber };
            ViewBag.id = student.RegistrationNumber;

            if (courses != null) 
            {
                return View(courses);
            }
            return View();
        }






    

       
        public async Task<IActionResult> TotalGrade(int? id)
        {
            
            var student = await _context.Students
                 .Include(s => s.UsersUsernameNavigation)
                 .FirstOrDefaultAsync(m => m.RegistrationNumber == id);
            ViewBag.id = student.RegistrationNumber;
            var courses = from stud in _context.Students
                          join courseGrades in _context.CourseHasStudents on stud.RegistrationNumber equals courseGrades.StudentsRegistrationNumber
                          into res1
                          from item in res1
                          join course in _context.Courses on item.CourseIdCourse equals course.IdCourse
                          where stud.RegistrationNumber == id && item.GradeCourseStudent != null
                          select new ViewModel
                          { grade = (int)item.GradeCourseStudent, title = course.CourseTitle, semester = course.CourseSemester };
            if (student == null)
            {
                return NotFound();
            }
            float totalGrade = 0;
            foreach (var item in courses) 
            {
                totalGrade += item.grade;
            }
            if (courses.Count() > 0)
            {
                totalGrade = totalGrade / courses.Count();
            }
            return View(ViewBag.Total = totalGrade);
        }

        
        

      
        private bool StudentExists(int id)
        {
          return _context.Students.Any(e => e.RegistrationNumber == id);
        }
    }
}

UniversitySystemWeb/Views/Shared/ProfessorLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversitySystemWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversitySystemWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">University Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="@ViewBag.id" asp-controller="Professors" asp-action="ViewNotGraded">Insert Grades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="@ViewBag.id" asp-controller="Professors" asp-action="ViewGrade">View Grades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UniversitySystemWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UniversitySystemWeb/Views/Shared/SecretaryLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversitySystemWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversitySystemWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">University Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""  asp-controller="Secretaries" asp-action="InsertCourse">Insert Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Secretaries" asp-action="InsertProfessor">Insert Professor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""  asp-controller="Secretaries" asp-action="InsertStudent">Insert Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""  asp-controller="Secretaries" asp-action="ViewCourses">View Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UniversitySystemWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UniversitySystemWeb/Views/Shared/StudentLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversitySystemWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversitySystemWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">University Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="@ViewBag.id" asp-controller="Students" asp-action="GradePerCourse">Grade per course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="@ViewBag.id" asp-controller="Students" asp-action="GradePerSemester">Grade per semester</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="@ViewBag.id" asp-controller="Students" asp-action="TotalGrade">Total grade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UniversitySystemWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UniversitySystemWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversitySystemWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversitySystemWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">University Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UniversitySystemWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>