UniversitySystemWeb/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversitySystemWeb.Models;

[Table("professors")]
public partial class Professor
{
    [Key]
    [Column("AFM")]
    public int Afm { get; set; }

    [StringLength(45)]
    [Unicode(false)]
    public string? Name { get; set; }

    [StringLength(45)]
    [Unicode(false)]
    public string? Surname { get; set; }

    [StringLength(45)]
    [Unicode(false)]
    public string? Department { get; set; }

    [Column("USERS_username")]
    [StringLength(45)]
    [Unicode(false)]
    public string UsersUsername { get; set; } = null!;

    [InverseProperty("ProfessorsAfmNavigation")]
    public virtual ICollection<Course> Courses { get; } = new List<Course>();

    [ForeignKey("UsersUsername")]
    [InverseProperty("Professors")]
    public virtual User UsersUsernameNavigation { get; set; } = null!;
}

UniversitySystemWeb/Controllers/CourseHasStudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversitySystemWeb.Models;

namespace UniversitySystemWeb.Controllers
{
    public class CourseHasStudentsController : Controller
    {
        private readonly GraderDBContext _context;

        public CourseHasStudentsController(GraderDBContext context)
        {
            _context = context;
        }

        // GET: CourseHasStudents
        public async Task<IActionResult> Index()
        {
       
            return View();
        }

        

       


        // GET: CourseHasStudents/Edit/5
        public async Task<IActionResult> InsertGrade(int courseId,int professorId,int registrationNumber,string courseName)
        {
            ViewBag.courseId = courseId;
            ViewBag.professorId = professorId;
            ViewBag.regNumber = registrationNumber;
            ViewBag.name = courseName;
            if (courseId == null || _context.CourseHasStudents == null)
            {
                return NotFound();
            }

            var courseHasStudent = await _context.CourseHasStudents.FindAsync(courseId,registrationNumber);
            if (courseHasStudent == null)
            {
                return NotFound();
            }
           
            return View(courseHasStudent);
        }





        // POST: CourseHasStudents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertGrade(int courseId,int professorId, int registrationNumber, [Bind("CourseIdCourse,StudentsRegistrationNumber,GradeCourseStudent")] CourseHasStudent courseHasStudent)
        {
            if (courseHasStudent.CourseIdCourse==0)
            {
                return NotFound();
            }
                try
                {
                    _context.Update(courseHasStudent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseHasStudentExists(courseHasStudent.CourseIdCourse))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
            }
            
            return RedirectToAction("ViewGrade", "Professors", new {id=professorId});
        }

       

        // POST: CourseHasStudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CourseHasStudents == null)
            {
                return Problem("Entity set 'GraderDBContext.CourseHasStudents'  is null.");
            }
            var courseHasStudent = await _context.CourseHasStudents.FindAsync(id);
            if (courseHasStudent != null)
            {
                _context.CourseHasStudents.Remove(courseHasStudent);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseHasStudentExists(int id)
        {
          return _context.CourseHasStudents.Any(e => e.CourseIdCourse == id);
        }
    }
}

UniversitySystemWeb/Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversitySystemWeb.Models;

namespace UniversitySystemWeb.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly GraderDBContext _context;

        public ProfessorsController(GraderDBContext context)
        {
            _context = context;
        }

        // GET: Professors
        public async Task<IActionResult> Index(string username)
        {
            var professor = await _context.Professors
                .Include(s => s.UsersUsernameNavigation)
                .FirstOrDefaultAsync(m=> m.UsersUsername==username);
            ViewBag.id = professor.Afm;
            if (professor != null)
            {
                return View(professor);
            }
            return NotFound();
        }

        



    

        public async Task<IActionResult> ViewGrade(int? id,string cTitle = "") 
        {
            
            ViewBag.id = id;
            var courses = (from course in _context.Courses
                          join courseGrades in _context.CourseHasStudents on course.IdCourse equals courseGrades.CourseIdCourse
                          into result
                          from item in result
                          join prof in _context.Professors on course.ProfessorsAfm equals prof.Afm
                          where item.GradeCourseStudent != null && course.ProfessorsAfm==id
                          select new ViewModel
                          { grade = (int)item.GradeCourseStudent, title = course.CourseTitle, semester = course.CourseSemester, registrationNumber = (int)item.StudentsRegistrationNumber }).OrderBy(x=>x.semester);

            var titles = new List<string>(courses.Select(x => x.title).Distinct());
            List<SelectListItem> courseTitles  = titles.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.ToString(),
                    Value = a.ToString(),
                    Selected = false
                };
            });
            
            ViewBag.cTitle = cTitle;

            ViewBag.courseTitles = courseTitles;
            if (courses != null) 
            {
                return View(courses);
            }             
            return View();
        }

        public async Task<IActionResult> ViewNotGraded(int? id)
        {
           
            ViewBag.id = id;
            var courses = (from course in _context.Courses
                          join courseGrades in _context.CourseHasStudents on course.IdCourse equals courseGrades.CourseIdCourse
                          into result
                          from item in result
                          join prof in _context.Professors on course.ProfessorsAfm equals prof.Afm
                          where item.GradeCourseStudent == null && course.ProfessorsAfm == id
                           select new ViewModel
                          { title = course.CourseTitle, semester = course.CourseSemester, registrationNumber = (int)item.StudentsRegistrationNumber,professorId = (int)id, courseId=item.CourseIdCourse }).OrderBy(x=>x.semester);
            
            if (courses != null)
            {
                return View(courses);
            }
            return View();
        }

        public IActionResult Create(string username)
        {
            ViewData["UsersUsername"] = new SelectList(_context.Users, "Username", "Username");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string username,[Bind("Afm,Name,Surname,Department,UsersUsername")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professor);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Secretaries", new { username = username });
            }
            return NotFound();
            
        }




        private bool ProfessorExists(int id)
        {
          return _context.Professors.Any(e => e.Afm == id);
        }
        private bool CourseHasStudentExists(int id)
        {
            return _context.CourseHasStudents.Any(e => e.CourseIdCourse == id);
        }
    }
}

UniversitySystemWeb/Views/Professors/Create.cshtml
@model UniversitySystemWeb.Models.Professor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CourseHasStudent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Afm" class="control-label"></label>
                <input asp-for="Afm" class="form-control" />
                <span asp-validation-for="Afm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" id="username" name="username" class="form-control" value="@ViewBag.username" />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UniversitySystemWeb/Views/Professors/Index.cshtml
@model UniversitySystemWeb.Models.Professor

@{
    ViewData["Title"] = "Index";
}

<h1>Your information</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Afm)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Afm)
            </td>
        </tr>
    </tbody>
</table>

UniversitySystemWeb/Views/Professors/ViewGrade.cshtml
@model IEnumerable<ViewModel>


@{
    ViewData["Title"] = "ViewGrade";
    var filteredModels = Model.Select(s=>s.title == ViewBag.title);
}

<h2>Graded students per course</h2>
<div>
    @using (Html.BeginForm("ViewGrade", "Professors"))
    {
        @Html.AntiForgeryToken()
        <div class=" form-group">
            <fieldset>

            Course Title

                @Html.DropDownList("cTitle", (IEnumerable
            <SelectListItem>)ViewBag.courseTitles)

    </fieldset>

            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-primary" />
            </div>
        </div>
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Course Title
            </th>
            <th>
                Course Semester
            </th>
            <th>
                Student
            </th>
            <th>
                Course Grade
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            if (item.title == @ViewBag.cTitle)
            {
                 <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.title )
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.semester)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.registrationNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.grade)
                </td>
            </tr>
            }
         }
           
    </tbody>
</table>

UniversitySystemWeb/Views/Professors/ViewNotGraded.cshtml
@model IEnumerable<ViewModel>
@{
    ViewData["Title"] = "ViewNotGraded";
   
}

<h2>Ungraded students</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Course Title
            </th>
            <th>
                Course Semester
            </th>
            <th>
                Student ID
            </th>
            <th>
                Insert grade
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.title )
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.semester)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.registrationNumber)
                    </td>
                <td>
                    @Html.ActionLink("Insert Grade", "InsertGrade","CourseHasStudents", 
                    new { courseId = item.courseId,professorId = item.professorId, registrationNumber = item.registrationNumber,courseName = item.title})
                    
                </td>
                </tr>
        }

    </tbody>
</table>